site_name: MAST-U IMAS Mappings
site_author: Adam Parker
site_description: >-
  JSON Mapping Plugin documentation for mapping experiment fusion data 
  into ITER IDS format

# Repository
repo_name: UKAEA/IMAS_MASTU_mappings
repo_url: https://github.com/adam-parker1/IMAS_MASTU_mappings

# Copyright
copyright: Copyright &copy; 2022-2024 Adam Parker

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  # custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto Bold 700
    code: Roboto Mono Bold 700
  favicon: assets/favicon.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# nav tree
nav:
  - Home: 'index.md'
  # - Extra: 'map_types/value_map.md'
  - IDS Mappings: 
    - magnetics:
      - overview: 'mappings/magnetics/overview.md'
      - mappings: 'mappings/magnetics/mappings.md'
    - pf_active:
      - overview: 'mappings/pf_active/overview.md'
      - mappings: 'mappings/pf_active/mappings.md'
    - pf_passive:
      - overview: 'mappings/pf_passive/overview.md'
      - mappings: 'mappings/pf_passive/mappings.md'
    - wall:
      - overview: 'mappings/wall/overview.md'
      - mappings: 'mappings/wall/mappings.md'
    - tf:
      - overview: 'mappings/tf/overview.md'
      - mappings: 'mappings/tf/mappings.md'
    - equilibrium:
      - overview: 'mappings/equilibrium/overview.md'
      - mappings: 'mappings/equilibrium/mappings.md'
    - summary:
      - overview: 'mappings/summary/overview.md'
      - mappings: 'mappings/summary/mappings.md'
