[build-system]
requires = ["setuptools>=69.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imas-mastu-mappings"
version = "0.1.0"
description = "JSON Mapping Plugin documentation for mapping experiment fusion data into ITER IDS format"
authors = [
    {name = "Adam Parker"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "attrs>=23.1.0",
    "cexprtk>=0.4.1",
    "Cython>=3.0.10",
    "jsonschema>=4.21.1",
    "numpy>=1.26.4",
    "pytest>=8.1.1",
]

[project.optional-dependencies]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "pymdown-extensions>=10.11.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
